apiVersion: apps/v1
kind: Deployment
metadata:
  name: light-house
spec:
  replicas: 2
  selector:
    matchLabels:
      app: light-house
  template:
    metadata:
      labels:
        app: light-house
    spec:
      # If your Docker Hub repo is private, add imagePullSecrets here:
      # imagePullSecrets:
      #   - name: dockerhub-regcred
      containers:
        - name: light-house
          image: mujju752/light-house:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
