apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: light-house
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/muzzammil-hamdu/light-house.git'
    targetRevision: main
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: light-house
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
