apiVersion: v1
kind: Service
metadata:
  name: light-house-lb
  labels:
    app: light-house
spec:
  type: LoadBalancer
  selector:
    app: light-house
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
